### ISSUE TITLE
Automatic Tracking Error

### ISSUE THREAD

**Issue by Abbabon** [ilastik/ilastik-build-win64#11]
I'm getting this on all my machines (using 1.1.6) - 

Hi people, I keep getting this error with all my Windows machines trying to run Automatic Tracking (during the tracking phase). Didn't know where else to turn for help :(

ERROR 2015-09-02 03:14:07,128 log_exception 7592 9420 Traceback (most recent call last):
File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\tracking\conservation\conservationTrackingGui.py", line 207, in _track
disappearance_cost = disappearanceCost
File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\tracking\conservation\opConservationTracking.py", line 210, in track
events = get_events(eventsVector)
File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\tracking\base\trackingUtilities.py", line 72, in get_events
events[str(t)] = get_events_at(eventsVector, t)
File "C:\Program Files\ilastik-1.1.6\ilastik\ilastik\ilastik\applets\tracking\base\trackingUtilities.py", line 91, in get_events_at
mov.append((event.traxel_ids[0], event.traxel_ids[1], event.energy))
TypeError: No Python class registered for C++ class class std::vector >

ERROR 2015-09-02 03:14:07,130 log_exception 7592 9420 Error during tracking. See above error traceback.

what am I doing wrong?

**Comment by chaubold** [comment]
Hi Abbabon,

most of our ilastik related bug reports are going to the main ilastik repo (https://github.com/ilastik/ilastik), but your problem might be related to the configuration in the windows build, so this is the right place to turn to for help!

Could you give us some more information to help us narrow down the issue please?
- this happened when running tracking, not while loading a project, right?
- in your User's home directory there should be a file `.ilastik_log.txt` containing above error message. In the line `TypeError: No Python class registered for C++ class class std::vector >` I am missing a type before the closing > (could look like this: `std::vector<unsigned int>`). Could you please have a look at that file - or reproduce the error message - and let us know which type this is referring to?

Thanks,
Carsten
